apiVersion: v2
name: geoserver
version: 0.3.1
appVersion: 2.17.0
description: Chart for GeoServer
keywords:
  - GeoServer
  - GIS
home: http://geoserver.org
sources:
  - https://github.com/geoserver/geoserver
maintainers:
  - name: lucernae
    email: lana.pcfre@gmail.com
engine: gotpl
icon: https://raw.githubusercontent.com/kartoza/charts/master/assets/logo/GeoServer_500.png
