{{- if .Values.extraConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.extraConfigMap }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end -}}
