{{- define "postgis.secret" -}}
data:
  {{- if not .Values.existingSecret }}
  postgresql-user: {{ .Values.postgresqlUsername | b64enc | quote }}
  {{- $postgresqlPassword := include "common.stickySecretValue" (dict "Config" .Values.postgresqlPassword "Context" . ) }}
  {{ include "common.secretKey" .Values.postgresqlPassword | nindent 2 }}: {{ $postgresqlPassword | b64enc | quote }}
  {{- $param := dict "Password" $postgresqlPassword "Context" . }}
  database-url: {{ (include "postgresql.connectionstring" $param ) | b64enc | quote }}
  {{- end }}
  {{- with .Values.extraSecret }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end -}}

{{- if or (not .Values.existingSecret) .Values.extraSecret }}
{{- include "common.secret" (list . "postgis.secret") -}}
{{- end }}
